// sandbox-client-vue/src/views/ModalMaisInformacoes.vue
<template>
  <v-dialog v-model="internalShow" max-width="600">
    <v-card>
      <v-card-title class="bg-surface text-on-surface d-flex align-center justify-space-between">
        {{ foundMovie.title }}
        <v-spacer></v-spacer>
        <v-btn color="error" class="text-center" icon="close" @click="closeModal"/>
      </v-card-title>

      <v-card-text class="bg-surface text-on-surface">
        <p>{{ foundMovie.description }}</p>
        <v-img v-if="foundMovie.imageUrl"
               :src="foundMovie.imageUrl"
               alt="Imagem do filme"
               max-height="300"
               contain></v-img>
      </v-card-text>

      <v-card-actions class="bg-surface text-on-surface">
        <v-spacer/>
        <v-btn color="secondary" @click="closeModal">Fechar</v-btn>
      </v-card-actions>
    </v-card>
  </v-dialog>
</template>

<script setup>
import {ref, watch} from 'vue'
import api from '@/services/api'

const props = defineProps({
  show: Boolean,
  selectedMovie: String,
})

const emit = defineEmits(['update:show'])
const internalShow = ref(props.show)
const foundMovie = ref({})

watch(() => props.show, (val) => {
  internalShow.value = val
  if (val && props.selectedMovie) {
    fetchMovie()
  }
})

watch(internalShow, (val) => {
  if (!val) emit('update:show', false)
})

async function fetchMovie() {
  try {
    const res = await api.get(`/movies/${props.selectedMovie}`)
    foundMovie.value = res.data
  } catch (err) {
    console.error('Erro ao buscar filme:', err)
  }
}

function closeModal() {
  internalShow.value = false
}

</script>

// react_app/src/components/ModalMaisInformacoes.js
import React, { useEffect, useState } from 'react';
import { Modal, Button } from 'react-bootstrap';
import api from "../services/api"

function ModalMaisInformacoes({ selectedMovie, show, handleClose }) {

    const [foundMovie, setFoundMovie] = useState({});

    useEffect(() => {

        if (selectedMovie === '' && show) {
            return;
        }

        api.get(`/movies/${selectedMovie}`)
           .then((response) => setFoundMovie(response.data))
           .catch((err) => {
               console.error("ops! ocorreu um erro" + err);
           });
    }, [selectedMovie, show]);

    return (
        <>
            <Modal show={show} onHide={handleClose} centered>
                <Modal.Header closeButton className="bg-dark text-white">
                    <Modal.Title>{foundMovie.title}</Modal.Title>
                </Modal.Header>

                <Modal.Body className="bg-dark text-white">
                    <p>{foundMovie.description}</p>
                    <img alt='' src={foundMovie.imageUrl} />
                </Modal.Body>

                <Modal.Footer className="bg-dark text-white">
                    <Button variant="secondary" onClick={handleClose}>
                        Fechar
                    </Button>
                </Modal.Footer>
            </Modal>
        </>
    )
}

export default ModalMaisInformacoes;
